### PR TITLE
Added necessary lines to produce the accurate reference to the specs

### PR DESCRIPTION
**Pull request by jccguimaraes**
This references issue #12.

### CODE REVIEW

**Comment by kentcdodds** [comment]
LGTM. Not sure what's up with Travis. cc @jfmengels?

**Comment by jccguimaraes** [comment]
didn't notice that travis would run without a `.travisrc`... github integration?

**Comment by jfmengels** [comment]
Thanks a lot @jccguimaraes! I've released this in `v3.0.3` and added you to the contributors list :)

As for Travis, yeah, I never set it up correctly for this project it seems... my bad.

**Comment by jccguimaraes** [comment]
No problem @jfmengels, glad to help.
If you need more help, just shout!

**Pull request merged**
