### PR TITLE
Add empty last line to the contributors file.

### PR DESCRIPTION
**Pull request by ben-eb**
This was bugging me so I fixed it for you; also reduces a bit of duplication.

PS: You might want to fix the contributors file! https://github.com/jfmengels/all-contributors-cli/commit/b7e5976e445c087ac334b3c2b3721a1a1f90403e

### CODE REVIEW

**Comment by jfmengels** [comment]
Hey ! Thanks a lot @ben-eb!

I totally get why this is bugging you, and :+1: for me on this.
I actually did have that at some point, but I removed it in https://github.com/jfmengels/all-contributors-cli/commit/cb5895dbfd44758cdfc255bb9112923bc4a2bbe2 when removing the comma-first style of the file (I hoped that it would create less conflicts).

@kentcdodds are you fine with this too?

If yes, I'll merge and re-add the previous collaborators. That's what you get when I use this project's contributors file to test the tool on :sweat_smile: (at least it was not regenerated and didn't show on the README :smile:).

**Comment by kentcdodds** [comment]
:shipit: :+1:

**Comment by jfmengels** [comment]
Thanks for the quick response @kentcdodds :D

Merged, fixed the collaborators, and published in v3.0.5.

Thanks again @ben-eb :)

**Comment by ben-eb** [comment]
Awesome! 👍

**Pull request merged**
