### PR TITLE
throw a helpful error when unknown contribution type is provided

### PR DESCRIPTION
**Pull request by jerodsanto**
As discussed in #40. Happy to change whatever to fit project style/best practices. 💚

### CODE REVIEW

**Comment by kentcdodds** [comment]
Would you like to [add yourself](../blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor) to the [contributors table](../#contributors)?

**Comment by jerodsanto** [comment]
@kentcdodds added, thanks! 

Note: the npm scripts for this project don't include `all-contributors` commands yet, so I just used my global version instead. ¯\_(ツ)_/¯

**Comment by kentcdodds** [comment]
Whoops! I should probably clean up this project and make it more contributor friendly (if you don't mind @jfmengels) :)

**Comment by kentcdodds** [comment]
Thank you so much!

**Comment by jfmengels** [comment]
> I should probably clean up this project and make it more contributor friendly (if you don't mind @jfmengels) :)

It's  good idea, feel free to do it :)

**Pull request merged**
