### PR TITLE
Promisify everything and bump inquirer to v3

### LINKED ISSUE #33: Arrow keys don't seem to work in Windows 10
I have tried to use the up/down arrow keys in both PowerShell and cmd.exe and the arrow keys seem to do nothing (the green '>' doesn't move)

### PR DESCRIPTION
**Pull request by jfmengels**
Should fix #33.

We had inquirer in v0.12, and the current version is v3, with v1 changing everything from callbacks to Promises. This is a breaking change as I use native Promises at some locations, and I figured this might well be the occasion to drop support for Node.js < v4.

@kentcdodds With semantic-release, I understand that this will be released upon merge, but I'm pretty sure I did not make that clear to the tool.

@tommck if you could test this locally in your Windows environment, that would be nice. I hope this fixes your issue.

### CODE REVIEW

**Comment by tommck** [comment]
Just tested this out locally.. arrow keys worked!

(Also learned how to use a git branch in an npm package.json file :) )

**Comment by jfmengels** [comment]
Fix released in v4. Hope it all works better for you now @tommck, and thanks for reporting and testing it out :)

**Comment by kentcdodds** [comment]
Awesome! Thanks @jfmengels, the release notes look awesome too by the way :)

**Comment by jfmengels** [comment]
Haha, I had to rewrite them actually :sweat_smile:. It pretty much showed what I put in the commit, but I didn't quite know how it was going to end up, and described a lot of internal stuff. I rewrote it to be more about the external changes. I'll know it better for the next time :smile:

**Pull request merged**
